//! Generated by `codegen/create_gen_atoms.py`
//! Creates array of predefined atoms
//! Config used: OTP28
#![allow(dead_code)]

use crate::term::*;


pub const SYM_PLUS: Term = Term::make_atom(0);
pub const SYM_MINUS: Term = Term::make_atom(1);
pub const SYM_EQ_EQ: Term = Term::make_atom(2);
pub const ALL: Term = Term::make_atom(3);
pub const APPLY: Term = Term::make_atom(4);
pub const BADARG: Term = Term::make_atom(5);
pub const BADARITH: Term = Term::make_atom(6);
pub const BADARITY: Term = Term::make_atom(7);
pub const BADFUN: Term = Term::make_atom(8);
pub const BADKEY: Term = Term::make_atom(9);
pub const BADMAP: Term = Term::make_atom(10);
pub const BADMATCH: Term = Term::make_atom(11);
pub const BADRECORD: Term = Term::make_atom(12);
pub const CASE_CLAUSE: Term = Term::make_atom(13);
pub const ERLANG: Term = Term::make_atom(14);
pub const ERROR: Term = Term::make_atom(15);
pub const ERTS_INTERNAL: Term = Term::make_atom(16);
pub const EXIT: Term = Term::make_atom(17);
pub const FALSE: Term = Term::make_atom(18);
pub const FUNCTION_CLAUSE: Term = Term::make_atom(19);
pub const HIGH: Term = Term::make_atom(20);
pub const IF_CLAUSE: Term = Term::make_atom(21);
pub const INIT: Term = Term::make_atom(22);
pub const KILL: Term = Term::make_atom(23);
pub const KILLED: Term = Term::make_atom(24);
pub const LOW: Term = Term::make_atom(25);
pub const NIF_ERROR: Term = Term::make_atom(26);
pub const NOCATCH: Term = Term::make_atom(27);
pub const NORMAL: Term = Term::make_atom(28);
pub const OK: Term = Term::make_atom(29);
pub const SYSTEM_LIMIT: Term = Term::make_atom(30);
pub const THROW: Term = Term::make_atom(31);
pub const TRAP_EXIT: Term = Term::make_atom(32);
pub const TRUE: Term = Term::make_atom(33);
pub const UNDEF: Term = Term::make_atom(34);
pub const UNDEFINED: Term = Term::make_atom(35);

pub static ATOM_INIT_NAMES: &'static [&'static str] = &[
  "+", // id=0
  "-", // id=1
  "==", // id=2
  "all", // id=3
  "apply", // id=4
  "badarg", // id=5
  "badarith", // id=6
  "badarity", // id=7
  "badfun", // id=8
  "badkey", // id=9
  "badmap", // id=10
  "badmatch", // id=11
  "badrecord", // id=12
  "case_clause", // id=13
  "erlang", // id=14
  "error", // id=15
  "erts_internal", // id=16
  "exit", // id=17
  "false", // id=18
  "function_clause", // id=19
  "high", // id=20
  "if_clause", // id=21
  "init", // id=22
  "kill", // id=23
  "killed", // id=24
  "low", // id=25
  "nif_error", // id=26
  "nocatch", // id=27
  "normal", // id=28
  "ok", // id=29
  "system_limit", // id=30
  "throw", // id=31
  "trap_exit", // id=32
  "true", // id=33
  "undef", // id=34
  "undefined", // id=35
];
